/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pk_Vista.Insert;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import pk_CRUD.Cls_Cerveza;
import pk_CRUD.Cls_Expendio;
import pk_CRUD.Cls_Presentacion;
import pk_Modelo.Almacen;
import pk_Modelo.Cerveza;
import pk_Modelo.Expendio;
import pk_Modelo.Presentacion;
import pk_Vista.Preview.Frm_AlmacenPrev;

/**
 *
 * @author jadey
 */
public class Frm_Almacen extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Almacen
     */
    
    ArrayList<Cerveza> listCerveza;
    ArrayList<Expendio> listExpendio;
    ArrayList<Presentacion> listPresentacion;
    
    public Frm_Almacen() {
        initComponents();
        setLocationRelativeTo(null);
        
        llenarCerveza();
        llenarExpendio();
        
        cmb_Presentacion.setEnabled(false);
    }
    
    
    private void llenarCerveza(){
         listCerveza=new Cls_Cerveza().getCervezas();
        for (int i = 0; i < listCerveza.size(); i++) {
            Cerveza c =listCerveza.get(i);
            cmb_Cerveza.addItem(c.getCer_Nombre());
        }
        cmb_Cerveza.setSelectedIndex(-1);
    }

    private void llenarExpendio(){
         listExpendio = new Cls_Expendio().getExpendios();
        for (int i = 0; i < listExpendio.size(); i++) {
            Expendio e =listExpendio.get(i);
            cmb_Expendio.addItem(e.getExp_Nombre());
        }
        cmb_Expendio.setSelectedIndex(-1);
    }
    
    private void llenarPresentacion(int id_cerveza){
         listPresentacion = new Cls_Presentacion().getPresentaciones(id_cerveza);
        for (int i = 0; i < listPresentacion.size(); i++) {
            Presentacion p =listPresentacion.get(i);
            cmb_Presentacion.addItem(p.getPre_tipo_envase()+" "+p.getPre_capacidad());
        }
        cmb_Presentacion.setSelectedIndex(-1);
    }
    
    public void limpiar(){
        cmb_Expendio.setSelectedIndex(-1);
        cmb_Cerveza.setSelectedIndex(-1);
        cmb_Presentacion.setSelectedIndex(-1);
        txt_Capacidad.setText("");
        txt_Existencia.setText("");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmb_Expendio = new javax.swing.JComboBox<>();
        cmb_Presentacion = new javax.swing.JComboBox<>();
        txt_Existencia = new javax.swing.JTextField();
        txt_Capacidad = new javax.swing.JTextField();
        btn_Agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_Cerveza = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Presentación:");

        jLabel2.setText("Existencia:");

        jLabel3.setText("Expendio:");

        jLabel4.setText("Capacidad:");

        jLabel5.setText("Cerveza");

        cmb_Cerveza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_CervezaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Agregar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_Presentacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_Expendio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Existencia)
                            .addComponent(txt_Capacidad, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(cmb_Cerveza, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_Expendio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_Cerveza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmb_Presentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Existencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btn_Agregar)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_CervezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_CervezaActionPerformed
        // TODO add your handling code here:
        cmb_Presentacion.removeAllItems();
        int id_cerveza = cmb_Cerveza.getSelectedIndex();
        
        cmb_Presentacion.setEnabled(true);
        
        llenarPresentacion(id_cerveza+1);
    }//GEN-LAST:event_cmb_CervezaActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        // TODO add your handling code here:
        int idExpendio = cmb_Expendio.getSelectedIndex();
        int idCerveza = cmb_Cerveza.getSelectedIndex();
        int idPresentacion = cmb_Presentacion.getSelectedIndex();
        int capacidad = 0, existencia = 0;
        String capacidadtxt = txt_Capacidad.getText();
        String existenciatxt = txt_Existencia.getText();
        
        StringBuilder mensajeError = new StringBuilder();
        
        if (idExpendio == -1) {
            mensajeError.append("Debe seleccionar un expendio válido.\n");
        } else {
            Expendio e = listExpendio.get(idExpendio);
            if (e.getId_Expendio()< 0) {
                mensajeError.append("El expendio seleccionado no es valido.\n");
            }
        }
        
        if (idCerveza == -1) {
            mensajeError.append("Debe seleccionar una cerveza válido.\n");
        } else {
            Expendio e = listExpendio.get(idExpendio);
            if (e.getId_Expendio()< 0) {
                mensajeError.append("La cerveza seleccionada no es valida.\n");
            }
        }
        
        if (idPresentacion == -1) {
            mensajeError.append("Debe seleccionar una presentacion válida.\n");
        } else {
            Presentacion p = listPresentacion.get(idPresentacion);
            if (p.getId_presentacion()< 0) {
                mensajeError.append("La presentacion seleccionada no es valida.\n");
            }
        }
        
        if (capacidadtxt.isEmpty()) {
            mensajeError.append("El campo de capacidad no puede estar vacío.\n");
        } else {
            try {
                capacidad = Integer.parseInt(capacidadtxt);

                if (capacidad <= 0) {
                    mensajeError.append("La cantidad no puede ser negativa o nula.\n");
                }
            } catch (NumberFormatException e) {
                mensajeError.append("El valor de cantidad debe ser un número entero válido.\n");
            }
        }
        
        if (existenciatxt.isEmpty()) {
            mensajeError.append("El campo de existencias no puede estar vacío.\n");
        } else {
            try {
                existencia = Integer.parseInt(existenciatxt);

                if (existencia < 0) {
                    mensajeError.append("La Existencia no puede ser negativa.\n");
                }
            } catch (NumberFormatException e) {
                mensajeError.append("El valor de existencia debe ser un número entero válido.\n");
            }
        }
        if (existencia > capacidad) {
            mensajeError.append("El valor de la existencia no puede superar a la capacidad del almacen.\n");
        }
        
        if (mensajeError.length() > 0) {
            JOptionPane.showMessageDialog(null, mensajeError.toString(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            int idExp = listExpendio.get(idExpendio).getId_Expendio();
            //int idCer = listCerveza.get(idCerveza).getId_Cerveza();
            int idPre = listPresentacion.get(idPresentacion).getId_presentacion();
            
            String nombreExpendio = listExpendio.get(idExpendio).getExp_Nombre();
            String nombreCerveza = listCerveza.get(idCerveza).getCer_Nombre();
            String nombrePresentacion = cmb_Presentacion.getSelectedItem().toString(); 
            
            Almacen almacen = new Almacen(0,existencia,capacidad,
                    idPre,idExp);
            Frm_AlmacenPrev preview = new Frm_AlmacenPrev(this, almacen, nombreExpendio,
                    nombreCerveza, nombrePresentacion);
            
            preview.setVisible(true);
            this.setVisible(false);  
        }
    }//GEN-LAST:event_btn_AgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Almacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JComboBox<String> cmb_Cerveza;
    private javax.swing.JComboBox<String> cmb_Expendio;
    private javax.swing.JComboBox<String> cmb_Presentacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Capacidad;
    private javax.swing.JTextField txt_Existencia;
    // End of variables declaration//GEN-END:variables
}
