
package pk_Vista.Insert;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import pk_CRUD.Cls_Fabricante;
import pk_CRUD.Cls_Sede;
import pk_Modelo.Fabricante;
import pk_Modelo.Sede;
import pk_Vista.Preview.Frm_FabricantePrev;


public class Frm_Fabricante extends javax.swing.JFrame {

    ArrayList<Sede> list;
    private final Cls_Fabricante CA;
    private Fabricante f = null;
    
    public Frm_Fabricante() {
        initComponents();
        CA = new Cls_Fabricante();
        setTitle("Registro de Fabricantes");
        setLocationRelativeTo(null);       
        llenarSedes();
        f = null;
    }
    
    public Frm_Fabricante(Fabricante fabricante) {
        initComponents();
        CA = new Cls_Fabricante();
        setTitle("Registro de Fabricantes");
        setLocationRelativeTo(null);
        llenarSedes();
        int idSedeFabricante = fabricante.getId_Sede();

        for (Sede sede : list) { 
            if (sede.getId_Sede() == idSedeFabricante) {
                cb_Sede.setSelectedItem(sede.getSed_Nombre()); 
                break;
            }
        }

        txt_Nombre.setText(fabricante.getFab_Nombre());
        f = fabricante;
    }
  
    public void limpiar(){
        cb_Sede.setSelectedIndex(-1);
        txt_Nombre.setText("");
    }
    
    private void llenarSedes(){
//        Instancia la clase controladora (de pk_Crud)
        Cls_Sede o=new Cls_Sede();
//        Almacena el arraylist obtenido de getsedes en list
        list =o.getSedes();
//        se recorre el arraylist para añadir los elementos de "nombre" de cada índice de la lista al combobox
        for(int i=0; i<list.size();i++){
            Sede s=list.get(i);
            cb_Sede.addItem(s.getSed_Nombre()); //aquí necesita más detalles
        }
        cb_Sede.setSelectedIndex(-1);
    }
    
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_Fabricante = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        cb_Sede = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btn_Agregar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Sede");

        cb_Sede.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_SedeItemStateChanged(evt);
            }
        });
        cb_Sede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_SedeActionPerformed(evt);
            }
        });

        jLabel3.setText("Fabricante");

        btn_Agregar.setText("Confirmar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_FabricanteLayout = new javax.swing.GroupLayout(jp_Fabricante);
        jp_Fabricante.setLayout(jp_FabricanteLayout);
        jp_FabricanteLayout.setHorizontalGroup(
            jp_FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_FabricanteLayout.createSequentialGroup()
                .addGroup(jp_FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_FabricanteLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jp_FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Nombre)
                            .addComponent(cb_Sede, 0, 196, Short.MAX_VALUE)))
                    .addGroup(jp_FabricanteLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel3)
                        .addGap(0, 164, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_FabricanteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Cancelar)
                .addGap(34, 34, 34)
                .addComponent(btn_Agregar)
                .addGap(14, 14, 14))
        );
        jp_FabricanteLayout.setVerticalGroup(
            jp_FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_FabricanteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(53, 53, 53)
                .addGroup(jp_FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jp_FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Sede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jp_FabricanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Agregar)
                    .addComponent(btn_Cancelar))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_Fabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_Fabricante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_SedeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_SedeItemStateChanged
        
    }//GEN-LAST:event_cb_SedeItemStateChanged

    private void cb_SedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_SedeActionPerformed
        //Para seleccionar el id del elemento seleccionado en el combobox
        //Sede sede=list.get(cb_Sede.getSelectedIndex());
        //System.out.println("Id seleccionado:"+sede.getId_Sede());
    }//GEN-LAST:event_cb_SedeActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        String nombre = txt_Nombre.getText();
        int index_combo_sede = cb_Sede.getSelectedIndex(); // Obtener el índice seleccionado
        Sede sede = null;
        
        StringBuilder mensajeError = new StringBuilder();
        Frm_FabricantePrev preview;
    
        // Validación del campo de texto "nombre"
        if (nombre.isEmpty() || nombre.length() > 40 || nombre.length() < 3) {
            mensajeError.append("Longitud de nombre no válida (entre 3 y 40 caracteres).\n");
        }

        // Validación del JComboBox "cb_Sede"
        if (index_combo_sede == -1) { // No se ha seleccionado ninguna sede
            mensajeError.append("Debe seleccionar una sede válida.\n");
        } else {
            sede = list.get(index_combo_sede); // Obtener la sede seleccionada
            if (sede.getId_Sede() < 0) { 
                mensajeError.append("La sede seleccionada no es válida.\n");
            }
        }

        // Si hay errores, mostrar un mensaje
        if (mensajeError.length() > 0) {
            JOptionPane.showMessageDialog(null, mensajeError.toString(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Si no hay errores, declara el id que el usuario selecciono
            // int id_sede = list.get(id).getId_Sede();
            // String nombreSede = (String) cb_Sede.getSelectedItem();
            this.setVisible(false);
            if (f == null) {
                Fabricante fabricante = new Fabricante (0, nombre, sede.getId_Sede());
                preview = new Frm_FabricantePrev(Frm_Fabricante.this, fabricante, sede);                          
            } else {
                Fabricante fabricante = new Fabricante (f.getId_Fabricante(), nombre, sede.getId_Sede());
                preview = new Frm_FabricantePrev(Frm_Fabricante.this, fabricante, sede);
            }                       
            preview.setVisible(true); 
        }  
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Fabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Fabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Fabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Fabricante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Frm_Fabricante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JComboBox<String> cb_Sede;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jp_Fabricante;
    private javax.swing.JTextField txt_Nombre;
    // End of variables declaration//GEN-END:variables
}
