/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pk_Menu;

import javax.swing.JOptionPane;
import pk_Vista.Insert.Frm_Almacen;
import pk_Vista.Insert.Frm_Cerveza;
import pk_Vista.Insert.Frm_Expendio;
import pk_Vista.Insert.Frm_Fabricante;
import pk_Vista.Insert.Frm_Grano;
import pk_Vista.Insert.Frm_Lote;
import pk_Vista.Insert.Frm_Marca;
import pk_Vista.Insert.Frm_Pedido;
import pk_Vista.Insert.Frm_Presentacion;
import pk_Vista.Insert.Frm_Receta;
import pk_Vista.Insert.Frm_Sede;
import pk_Vista.Insert.Frm_Venta;

/**
 *
 * @author jadey
 */
public class Frm_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Menu
     */
    public Frm_Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private void openForm(String selectedTable) {
        switch (selectedTable) {
            case "Almacén":
                Frm_Almacen formAlma = new Frm_Almacen();
                formAlma.setVisible(true);
                this.dispose();
                break;
            case "Cerveza":
                Frm_Cerveza formCer = new Frm_Cerveza();
                formCer.setVisible(true);
                this.dispose();
                break;
            case "Expendio":
                Frm_Expendio formExp = new Frm_Expendio();
                formExp.setVisible(true);
                this.dispose();
                break;
            case "Fabricante":
                Frm_Fabricante formFab = new Frm_Fabricante();
                formFab.setVisible(true);
                this.dispose();
                break;
            case "Grano":
                Frm_Grano formGra = new Frm_Grano();
                formGra.setVisible(true);
                this.dispose();
                break;
            case "Lote":
                Frm_Lote formLot = new Frm_Lote();
                formLot.setVisible(true);
                this.dispose();
                break;
            case "Marca":
                Frm_Marca formMar = new Frm_Marca();
                formMar.setVisible(true);
                this.dispose();
                break;
            case "Pedido":
                Frm_Pedido formPed = new Frm_Pedido();
                formPed.setVisible(true);
                this.dispose();
                break;
            case "Presentación":
                Frm_Presentacion formPre = new Frm_Presentacion();
                formPre.setVisible(true);
                this.dispose();
                break;
            case "Receta":
                Frm_Receta formRec = new Frm_Receta();
                formRec.setVisible(true);
                this.dispose();
                break;
            case "Sede":
                Frm_Sede formSed = new Frm_Sede();
                formSed.setVisible(true);
                this.dispose();
                break;
            case "Venta":
                Frm_Venta formVen = new Frm_Venta();
                formVen.setVisible(true);
                this.dispose();
                break;
            // Añadir más casos para cada entidad que tengas
            default:
                JOptionPane.showMessageDialog(this, "Formulario no disponible para la entidad seleccionada.");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmb_Entidades = new javax.swing.JComboBox<>();
        btn_Info = new javax.swing.JLabel();
        btn_Buscar = new javax.swing.JLabel();
        txt_Opcion1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmb_Entidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almacén", "Cerveza", "Expendio", "Fabricante", "Grano", "Lote", "Marca", "Pedido", "Presentación", "Receta", "Sede", "Venta" }));
        cmb_Entidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_EntidadesActionPerformed(evt);
            }
        });
        cmb_Entidades.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb_EntidadesPropertyChange(evt);
            }
        });
        jPanel1.add(cmb_Entidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 140, -1));

        btn_Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_InfoMouseClicked(evt);
            }
        });
        jPanel1.add(btn_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 90, 60));

        btn_Buscar.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        btn_Buscar.setForeground(new java.awt.Color(0, 0, 0));
        btn_Buscar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_Buscar.setText("Buscar, modificar o eliminar  un registro");
        jPanel1.add(btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 370, 70));

        txt_Opcion1.setFont(new java.awt.Font("Gadugi", 1, 16)); // NOI18N
        txt_Opcion1.setForeground(new java.awt.Color(0, 0, 0));
        txt_Opcion1.setText("Agregar un registro");
        jPanel1.add(txt_Opcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk_Iconos/fondoMenu.png"))); // NOI18N
        fondo.setText("jLabel1");
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InfoMouseClicked
        Frm_Informacion formInfo = new Frm_Informacion();
        formInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_InfoMouseClicked

    private void cmb_EntidadesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb_EntidadesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_EntidadesPropertyChange

    private void cmb_EntidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_EntidadesActionPerformed
        // TODO add your handling code here:
        String selectedTable = (String) cmb_Entidades.getSelectedItem();
        openForm(selectedTable);
    }//GEN-LAST:event_cmb_EntidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Buscar;
    private javax.swing.JLabel btn_Info;
    private javax.swing.JComboBox<String> cmb_Entidades;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_Opcion1;
    // End of variables declaration//GEN-END:variables
}
